### ISSUE TITLE
Create a control panel for managing programs, episodes and broadcasts.

### ISSUE THREAD

**Issue by AdamJonsson** [glaufer/XTV#13]
I think It would be smart to split the control panel into three parts, programs, episodes and broadcast.

When editing broadcasts it would be nice to be able to click on an episode instead of writing in the ID manually. Like having a list on the left side with all the existing episodes like this:
![adminDemo](https://user-images.githubusercontent.com/13873828/69003896-1bdcce80-090a-11ea-9b77-5836dea139cb.jpg)

**Comment by glaufer** [comment]
Twitter API is ready. Integration with control panel needed when ready.

**Comment by AdamJonsson** [comment]
You can now also logout as a user from the admin page.
