### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by glaufer** [glaufer/XTV#4]
* [X] Find a way to set mini logo (Skipped)
* [X] Link each item to the program item on the website

**Comment by glaufer** [comment]
- One feed per channel
- Find a way to set mini logo

**Comment by glaufer** [comment]
- Find a way to set mini logo
- Link each item to the program item on the website

**Comment by AdamJonsson** [comment]
RSS links is fixed in ffcf0b6fca00cfbda723050e152ccaa30c80a83c 👍 

The mini logo is not added, do not know how to add it.

**Comment by glaufer** [comment]
I think we can skip it, I don't think that it matters. Some RSS readers
don't show a picture.

Den sön 1 dec. 2019 15:33Adam Jonsson <notifications@github.com> skrev:
